enableGlobalCache: true

pnpMode: loose
packageExtensions:
  "@remax/shared@*":
    dependencies:
      "lodash": "*"
      "resolve": "*"
      "postcss": "*"
  "@remax/build-store@*":
    dependencies:
      "lodash": "*"
  "@remax/cli@*":
    dependencies:
      "yargs-parser": "*"
      "@babel/parser": "*"
      "@babel/traverse": "*"
      "@remax/wechat": "*"
  "babel-plugin-remax-host-component@*":
    dependencies:
      "lodash": "*"
      "@remax/build-store": "*"
  "babel-plugin-remax-turbo-render@*":
    dependencies:
      "lodash": "*"
      "@remax/build-store": "*"
  "@remax/redbox-react@*":
    dependencies:
      "@remax/one": "*"
  "@remax/wechat@*":
    dependencies:
      "@remax/framework-shared": "*"
  "babel-plugin-remax-lifecycle@*":
    dependencies:
      "@remax/build-store": "*"

yarnPath: .yarn/releases/yarn-sources.cjs
